name: API Tests with Newman

on:
  push:
    branches: [ main ]   # Runs on every push to main
  pull_request:
    branches: [ main ]   # Also on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25.0.0'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Start backend server
      - name: Start backend server
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}   #  Atlas URI
          JWT_SECRET: ${{ secrets.JWT_SECRET }} #  JWT secret
          PORT: 5000
        run: |
          npm start &       # Start server in background
          sleep 10          # Wait for server to be ready

      # Step 5: Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Step 6: Run API tests
      - name: Run API tests
        run: |
          newman run TestAPI\task-api-collection.json -e TestAPI\task-env.json --reporters cli,html

      # Step 7: Upload HTML report
      - name: Upload test report
        if: always()   # Even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/*.html
